# Generated by Django 4.2.23 on 2025-10-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asistencia', models.CharField(choices=[('grua', 'Servicio de Grúa'), ('llanta', 'Cambio de Llanta'), ('gasolina', 'Suministro de Gasolina'), ('bateria', 'Recarga de Batería')], max_length=20)),
                ('ubicacion_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ubicacion_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aceptado', 'Aceptado por Conductor'), ('en_ruta_origen', 'En Ruta al Origen'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('auto', 'Automóvil (Viajes)'), ('moto', 'Motocicleta (Viajes y Envíos)'), ('bus', 'Autobús (Rutas Compartidas)'), ('camioneta', 'Camioneta (Asistencia Vial/Envío Grande)')], max_length=15)),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origen_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destino_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destino_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aceptado', 'Aceptado por Conductor'), ('en_ruta_origen', 'En Ruta al Origen'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('tarifa_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tarifa_final', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
