# Generated by Django 4.2.23 on 2025-10-24 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viaje',
            name='vehiculo_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(limit_choices_to={'rol__in': ['conductor', 'repartidor_domicilios']}, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudasistencia',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudasistencia',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_brindadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
