# Generated by Django 4.2.23 on 2025-10-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
    ]
