# Generated by Django 4.2.23 on 2025-10-25 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transporte', '0003_alter_vehiculo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='transporte.viaje')),
            ],
            options={
                'verbose_name': 'Mensaje de Viaje',
                'verbose_name_plural': 'Mensajes de Viaje',
                'ordering': ['timestamp'],
            },
        ),
    ]
