# Generated by Django 4.2.23 on 2025-11-06 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transporte', '0004_mensajeviaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaje',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Viaje', 'verbose_name_plural': 'Viajes'},
        ),
        migrations.AddField(
            model_name='viaje',
            name='nombre_destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='nombre_origen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='notas_conductor',
            field=models.TextField(blank=True, null=True, verbose_name='Notas para el Conductor'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='tipo_servicio',
            field=models.CharField(choices=[('economy', 'Economy (Auto Estándar)'), ('premium', 'Premium (Auto de Lujo)'), ('moto', 'Moto/Taxi (Rápido y Económico)')], default='economy', max_length=50, verbose_name='Tipo de Vehículo/Servicio Requerido'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
