# Generated by Django 4.2.23 on 2025-10-24 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('restaurante', 'Restaurante'), ('supermercado', 'Supermercado'), ('farmacia', 'Farmacia')], max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el comercio está recibiendo pedidos.')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('lat_entrega', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon_entrega', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aceptación'), ('preparando', 'En Preparación'), ('listo', 'Listo para Recoger'), ('en_camino', 'En Camino al Cliente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='domicilios.comercio')),
            ],
        ),
    ]
