# Generated by Django 4.2.23 on 2025-10-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_alter_vehiculo_options'),
        ('domicilios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='vehiculo_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='transporte.vehiculo', verbose_name='Vehículo Usado en el Pedido'),
        ),
    ]
